/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoneAuthRouteImport } from './routes/_noneAuth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as NoneAuthSignUpRouteImport } from './routes/_noneAuth/sign-up'
import { Route as NoneAuthLoginRouteImport } from './routes/_noneAuth/login'

const NoneAuthRoute = NoneAuthRouteImport.update({
  id: '/_noneAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const NoneAuthSignUpRoute = NoneAuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => NoneAuthRoute,
} as any)
const NoneAuthLoginRoute = NoneAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => NoneAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof NoneAuthLoginRoute
  '/sign-up': typeof NoneAuthSignUpRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof NoneAuthLoginRoute
  '/sign-up': typeof NoneAuthSignUpRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_noneAuth': typeof NoneAuthRouteWithChildren
  '/_noneAuth/login': typeof NoneAuthLoginRoute
  '/_noneAuth/sign-up': typeof NoneAuthSignUpRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/sign-up' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/sign-up' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_noneAuth'
    | '/_noneAuth/login'
    | '/_noneAuth/sign-up'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  NoneAuthRoute: typeof NoneAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_noneAuth': {
      id: '/_noneAuth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NoneAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_noneAuth/sign-up': {
      id: '/_noneAuth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof NoneAuthSignUpRouteImport
      parentRoute: typeof NoneAuthRoute
    }
    '/_noneAuth/login': {
      id: '/_noneAuth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof NoneAuthLoginRouteImport
      parentRoute: typeof NoneAuthRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface NoneAuthRouteChildren {
  NoneAuthLoginRoute: typeof NoneAuthLoginRoute
  NoneAuthSignUpRoute: typeof NoneAuthSignUpRoute
}

const NoneAuthRouteChildren: NoneAuthRouteChildren = {
  NoneAuthLoginRoute: NoneAuthLoginRoute,
  NoneAuthSignUpRoute: NoneAuthSignUpRoute,
}

const NoneAuthRouteWithChildren = NoneAuthRoute._addFileChildren(
  NoneAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  NoneAuthRoute: NoneAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
